import type { FastifyPluginAsync } from "fastify";
import type { ZodTypeProvider } from "fastify-type-provider-zod";
import {
  AnalyticsNarrativeRequest,
  AnalyticsNarrativeResponse,
  ApiError,
  AskDataApiRequest,
  AskDataRequest,
  AskDataResponse,
  DashboardMetrics,
} from "@peopleos/schemas";
import { withTenant } from "../db.js";
import { requireTenant, tenant } from "../plugins/tenancy.js";
import { forbidden } from "../lib/errors.js";
import { aiClient } from "../lib/aiClient.js";
import { buildOrgContext } from "../lib/orgContext.js";
import { computeDashboard } from "../lib/analytics.js";

/**
 * Module 5 — Workforce Analytics Dashboard. Mounted under /api/v1, tenant-scoped via
 * requireTenant + withTenant(orgId). This is a LEADERSHIP view (HR, People Ops,
 * managers), so it is restricted to ADMIN / HRBP / MANAGER — a plain EMPLOYEE or a
 * RECRUITER never sees org-wide workforce composition.
 *
 *   GET  /api/v1/analytics/dashboard   → DashboardMetrics (5a–5d, computed from Postgres)
 *   POST /api/v1/analytics/narrative   → AnalyticsNarrativeResponse (5e weekly narrative)
 *   POST /api/v1/analytics/ask         → AskDataResponse (5e "Ask your data" NL query)
 *
 * GROUNDING (prompt standard #2): for the two AI endpoints the API ALWAYS computes
 * the `DashboardMetrics` itself from Postgres and passes that exact snapshot to the AI
 * service. The client NEVER supplies metrics, and no SQL is ever generated by the LLM —
 * the AI narrates/answers strictly over the numbers the API gives it.
 *
 * EXPORT (spec 5 technical notes — follow-up): PDF report / CSV raw-data export and
 * scheduled push-to-Slack are out of scope for this slice. The intended design: a
 * GET /api/v1/analytics/dashboard.csv that serialises the same `computeDashboard`
 * snapshot, a PDF renderer over the narrative + charts, and a BullMQ scheduled job
 * that POSTs the narrative to a per-org Slack incoming webhook. None are built here.
 *
 * PROD DATA SOURCE (spec 5): metrics are materialised by scheduled DBT models in
 * Snowflake in production; `computeDashboard` is the dev/MVP Postgres path and the
 * shape authority (see src/lib/analytics.ts).
 */

/** Roles permitted to view workforce analytics (spec: HR, People Ops, leadership). */
const ANALYTICS_VIEW_ROLES = new Set(["ADMIN", "HRBP", "MANAGER"]);

const analyticsRoutes: FastifyPluginAsync = async (app) => {
  const r = app.withTypeProvider<ZodTypeProvider>();

  // ── 5a–5d: the computed dashboard ─────────────────────────────────────────────
  r.get(
    "/analytics/dashboard",
    {
      preHandler: requireTenant,
      schema: {
        tags: ["analytics"],
        summary: "Workforce analytics dashboard metrics (Module 5 — 5a-5d).",
        description:
          "Computes the full DashboardMetrics for the caller's org from Postgres (prod: Snowflake + DBT): recruiting funnel (5a), workforce composition (5b), and the pending engagement/retention (5c) + skills/talent (5d) sections (available:false until Modules 7/6 land). Leadership view — restricted to ADMIN/HRBP/MANAGER. Tenant-scoped via RLS.",
        response: { 200: DashboardMetrics, 401: ApiError, 403: ApiError },
      },
    },
    async (request) => {
      const { orgId, role } = tenant(request);
      if (!ANALYTICS_VIEW_ROLES.has(role)) {
        throw forbidden("Only ADMIN, HRBP, or MANAGER roles may view workforce analytics.");
      }
      return withTenant(orgId, (tx) => computeDashboard(tx, orgId));
    },
  );

  // ── 5e: weekly AI narrative ───────────────────────────────────────────────────
  r.post(
    "/analytics/narrative",
    {
      preHandler: requireTenant,
      schema: {
        tags: ["analytics"],
        summary: "AI narrative insights over the dashboard (Module 5e).",
        description:
          "Computes the DashboardMetrics server-side, then asks the AI service (Claude claude-sonnet-4-6) for the 'three most important people metrics' executive narrative plus > 2σ anomalies. The AI is grounded ONLY in the supplied metrics — it never invents numbers and never generates SQL. Leadership view — ADMIN/HRBP/MANAGER. Returns a 502 if the AI service is unavailable.",
        // No request body: the metrics are computed by the API, never client-supplied.
        response: {
          200: AnalyticsNarrativeResponse,
          401: ApiError,
          403: ApiError,
          502: ApiError,
        },
      },
    },
    async (request) => {
      const { orgId, role } = tenant(request);
      if (!ANALYTICS_VIEW_ROLES.has(role)) {
        throw forbidden("Only ADMIN, HRBP, or MANAGER roles may view workforce analytics.");
      }

      const { metrics, org } = await withTenant(orgId, async (tx) => {
        const computed = await computeDashboard(tx, orgId);
        const orgRow = await tx.organisation.findUnique({ where: { id: orgId } });
        return { metrics: computed, org: orgRow };
      });

      return aiClient.narrative(
        AnalyticsNarrativeRequest.parse({
          orgId,
          metrics,
          orgContext: buildOrgContext(org, role),
        }),
      );
    },
  );

  // ── 5e: "Ask your data" NL query ──────────────────────────────────────────────
  r.post(
    "/analytics/ask",
    {
      preHandler: requireTenant,
      schema: {
        tags: ["analytics"],
        summary: "Ask a natural-language question of the workforce data (Module 5e).",
        description:
          "Accepts ONLY a question; the API computes the DashboardMetrics server-side and hands them to the AI service, which answers grounded strictly in those metrics (no SQL is ever generated against the warehouse) and reports which metric keys it used. May return a chart spec. Leadership view — ADMIN/HRBP/MANAGER. 502 if the AI service is unavailable.",
        body: AskDataApiRequest,
        response: {
          200: AskDataResponse,
          400: ApiError,
          401: ApiError,
          403: ApiError,
          502: ApiError,
        },
      },
    },
    async (request) => {
      const { orgId, role } = tenant(request);
      if (!ANALYTICS_VIEW_ROLES.has(role)) {
        throw forbidden("Only ADMIN, HRBP, or MANAGER roles may view workforce analytics.");
      }
      const { question } = request.body;

      // The metrics are computed SERVER-SIDE — the client supplies only the question,
      // so a caller can never smuggle fabricated numbers in for the AI to "confirm".
      const { metrics, org } = await withTenant(orgId, async (tx) => {
        const computed = await computeDashboard(tx, orgId);
        const orgRow = await tx.organisation.findUnique({ where: { id: orgId } });
        return { metrics: computed, org: orgRow };
      });

      return aiClient.askData(
        AskDataRequest.parse({
          orgId,
          question,
          metrics,
          orgContext: buildOrgContext(org, role),
        }),
      );
    },
  );
};

export default analyticsRoutes;
