import * as React from "react";

import { cn } from "@/lib/utils";
import type {
  AnalyticsNarrativeResponse,
  Anomaly,
  FlagSeverity,
} from "@peopleos/schemas";

/**
 * NarrativePanel — the AI Narrative Insights surface (Module 5e). Renders the
 * weekly executive headline + 3-paragraph narrative ("the 3 most important
 * people metrics"), the surfaced `keyMetrics`, and any `anomalies` (metric > 2σ
 * from the org's own baseline), each coloured by `FlagSeverity`.
 *
 * The narrative is generated (claude-sonnet-4-6) grounded ONLY in the
 * API-computed metrics snapshot — it never invents numbers. This component is
 * presentational; it shows the model + prompt version for auditability.
 */

const SEVERITY_PILL: Record<FlagSeverity, string> = {
  HIGH: "border-destructive/40 bg-destructive/10 text-destructive",
  MEDIUM: "border-amber-600/40 bg-amber-600/10 text-amber-700",
  LOW: "border-blue-600/40 bg-blue-600/10 text-blue-700",
};

const SEVERITY_RANK: Record<FlagSeverity, number> = { HIGH: 0, MEDIUM: 1, LOW: 2 };

export function NarrativePanel({
  narrative,
  className,
}: {
  narrative: AnalyticsNarrativeResponse;
  className?: string;
}) {
  // Each narrative paragraph is split for readable spacing.
  const paragraphs = narrative.narrative
    .split(/\n{2,}/)
    .map((p) => p.trim())
    .filter(Boolean);

  const anomalies = [...narrative.anomalies].sort(
    (a, b) => SEVERITY_RANK[a.severity] - SEVERITY_RANK[b.severity],
  );

  return (
    <div className={cn("rounded-lg border bg-card p-5", className)}>
      <div className="flex items-start justify-between gap-3">
        <div className="space-y-1">
          <p className="text-[11px] font-medium uppercase tracking-wide text-muted-foreground">
            AI narrative insight
          </p>
          <h3 className="text-lg font-semibold leading-snug">
            {narrative.headline}
          </h3>
        </div>
      </div>

      <div className="mt-3 space-y-2 text-sm leading-relaxed text-foreground/90">
        {paragraphs.length > 0 ? (
          paragraphs.map((p, i) => <p key={i}>{p}</p>)
        ) : (
          <p>{narrative.narrative}</p>
        )}
      </div>

      {narrative.keyMetrics.length > 0 ? (
        <div className="mt-4 grid gap-2 sm:grid-cols-3">
          {narrative.keyMetrics.map((m, i) => (
            <div key={`${m.label}-${i}`} className="rounded-md border bg-background p-3">
              <p className="text-[11px] uppercase tracking-wide text-muted-foreground">
                {m.label}
              </p>
              <p className="mt-0.5 text-lg font-semibold tabular-nums">{m.value}</p>
              {m.note ? (
                <p className="mt-0.5 text-[11px] text-muted-foreground">{m.note}</p>
              ) : null}
            </div>
          ))}
        </div>
      ) : null}

      {anomalies.length > 0 ? (
        <div className="mt-4 space-y-2">
          <p className="text-xs font-medium text-foreground">
            Anomalies ({anomalies.length})
          </p>
          <ul className="space-y-2">
            {anomalies.map((a, i) => (
              <AnomalyRow key={`${a.metric}-${i}`} anomaly={a} />
            ))}
          </ul>
        </div>
      ) : null}

      <p className="mt-4 text-[10px] text-muted-foreground">
        Generated by {narrative.modelVersion}
        {narrative.promptVersion ? ` · prompt ${narrative.promptVersion}` : ""} ·
        grounded in the current metrics snapshot
      </p>
    </div>
  );
}

function AnomalyRow({ anomaly }: { anomaly: Anomaly }) {
  return (
    <li className="flex items-start gap-2 rounded-md border bg-background p-2.5">
      <span
        className={cn(
          "mt-0.5 inline-flex shrink-0 items-center rounded-full border px-1.5 py-0.5 text-[10px] font-medium uppercase tracking-wide",
          SEVERITY_PILL[anomaly.severity],
        )}
      >
        {anomaly.severity}
      </span>
      <div className="min-w-0">
        <p className="text-xs font-medium text-foreground">{anomaly.metric}</p>
        <p className="text-xs text-muted-foreground">{anomaly.detail}</p>
      </div>
    </li>
  );
}
